### ISSUE TITLE
Ability to run ocp-customization role as standalone playbook

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-playbooks#11]
Currently ocp-customization runs as part of install playbook. There should be a way to run ocp-customization as standalone playbook for customizing an installed OCP cluster

**Comment by schabrolles** [comment]
we could implement ansible tag. This will allow to run only this part if needed
https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html

**Comment by schabrolles** [comment]
@bpradipt 

A quick fix for this one (as I had to use it a lot yesterday). Tell me if this is what you expect.

to run it:
```
ansible-playbook -i inventory -e @install_vars.yaml playbook/customization.yaml
```

**Comment by bpradipt** [comment]
yes @schabrolles this is what I use as well
