### ISSUE TITLE
Create powervm-rmc project failure

### ISSUE THREAD

**Issue by cdhorn** [ocp-power-automation/ocp4-playbooks#161]
We have encountered the following error more than once recently when using the ocp4-upi-powervs Terraform pattern for deployments:

module.install.null_resource.install (remote-exec): TASK [ocp-customization : Create powervm-rmc project] **************************
module.install.null_resource.install (remote-exec): fatal: [cecc-7911-bastion-0]: FAILED! => {"changed": false, "msg": "Failed to find exact match for project.openshift.io/v1.Project by [kind, name, singularName, shortNames]"}

**Comment by aishwaryabk** [comment]
Thanks for reporting this. Can you please provide some more details like any specific variables provided, services/features that are enabled/disabled?

**Comment by cdhorn** [comment]
Sorry for delay in responding. 

This is a single node master/worker 4.8 deploy.  In the ocp4-upi-powervs I disable the master quantity validation check as these now seem to deploy okay and are what we are starting to provide to our users as they do not need a production environment and it is fewer resources. 

Bastion is running CentOS Streams 8 with Python 3.6.8-44, Ansible 2.9.27, pip installed openshift module at 0.13.1.  The OpenShift client and server levels are 4.8.36

**Comment by aishwaryabk** [comment]
Thanks for the details. I have tried deploying a 4.8 OCP cluster with 3 masters & 2 workers and it is running with all your specifications. I did not face any error while running the powervm-rmc playbook. 
Could you please give it a try with 3 masters as this is supported by the ocp4-upi-powervs automation?

**Comment by christopher-horn** [comment]
I have opened PR #162 with a tweak that addresses this that seems to work fine for us if you would please consider it for inclusion.
