### ISSUE TITLE
Automate Setting Node Labels for PowerVS 

### ISSUE THREAD

**Issue by aishwaryabk** [ocp-power-automation/ocp4-playbooks#164]
There are some well-known k8s labels that the RHACM UI uses ([failure-domain.beta.kubernetes.io/region](http://failure-domain.beta.kubernetes.io/region), [failure-domain.beta.kubernetes.io/zone](http://failure-domain.beta.kubernetes.io/zone), and [beta.kubernetes.io/instance-type](http://beta.kubernetes.io/instance-type)) and could be set for PowerVS nodes.

Ref: 
https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesioregion

**Comment by yussufsh** [comment]
https://github.com/ocp-power-automation/ocp4-playbooks/pull/163#issuecomment-1132619945

**Comment by yussufsh** [comment]
Also the labels should be a map variable so user can define or change the labels. @aishwaryabk could you please evaluate the changes?

**Comment by yussufsh** [comment]
Also no need to use the flag for setting the labels. If labels map is empty we do not run the tasks.

**Comment by aishwaryabk** [comment]
@yussufsh Modified the code to make use of a map variable for passing labels. Thank you.
