### ISSUE TITLE
Ability to configure "powervs nodes configuration" as variables

### ISSUE THREAD

**Issue by ghatwala** [ocp-power-automation/ocp4-playbooks#185]
Hi @Prajyot-Parab ,

Can you please add ability to configure these params - https://github.com/ocp-power-automation/ocp4-playbooks/blob/main/playbooks/roles/powervs-nodes-config/tasks/main.yaml#L14

**Comment by Prajyot-Parab** [comment]
Rephrase --> Make HTTP Proxy switch conditional and optional as part of "powervs nodes configuration" tasks if not set

**Comment by Prajyot-Parab** [comment]
PR - https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/483
PR - https://github.com/ocp-power-automation/ocp4-playbooks/pull/186
