### ISSUE TITLE
Additional reporting details required post OCP 4.x cluster install

### ISSUE THREAD

**Issue by arcprabh** [ocp-power-automation/ocp4-playbooks#37]
We need more output details to be included in the final output after the cluster gets installed. Please find the details below.

 1)  Output of ```oc get co```

   Although cluster install succeeds, some co's will be toggling between False and True or will remain in progressing state for a long time or forever. We need to wait for sometime to ensure all co states are True for Available column and False for Degraded and Progressing columns.

2) Output of ```oc get pods --all-namespaces```

   Some pods might have restarted multiple times, we need to identify and report such pods.
   Some pods might be in bad state, we need to display those pods status.

3) Report the logs and description of failed pods

4) Check and report the status of the storage class, sometimes it remains in Pending state.

5) Report the output of the below commands. It will be required to report a bug with all this information.

   oc get nodes
   openshift-install version
   oc get clusteroperators
   oc get clusterversion
   dmesg on nodes [ Run this and save it in some location and print that location on the output ]
   oc adm must-gather [ Run this and save it in some location and print that location on the output ]

**Comment by arcprabh** [comment]
@yussufsh @Prajyot-Parab - ptal

**Comment by yussufsh** [comment]
My initial thoughts: This is something you can do after login. Most of it is admin tasks post login. There could be N number of commands to validate/debug the cluster issue after install.
Also, adding the outputs to the automation will just increase the logs and installation time.

@bpradipt What you have to say?

**Comment by Prajyot-Parab** [comment]
I agree with @yussufsh on this one. Most of the commands are admin specific and need not be displayed after every cluster install always, @arcprabh maybe you can have a separate wrapper script on your end which admin can use later to get these details.
