### ISSUE TITLE
Setup Chrony on bastion node and let other nodes sync with bastion as a NTP server

### ISSUE THREAD

**Issue by yussufsh** [ocp-power-automation/ocp4-playbooks#38]
We need to perform following depending on the existing variable `chronyconfig.enabled` which is always `true`:

1. Install Chrony on bastion.
2. Enable and ensure ntp service is added to the bastion firewalld.
3. Add `chronyconfig.content` to chrony.conf on bastion if provided.
4. Allow Chrony to act as a server specific to cluster network using `allow` directive.
5. Update chrony config on bootstrap node to use bastion_ip as a server in iburst mode.
6. Update chrony config on master/worker nodes using MachineConfig to use bastion_ip as a server in iburst mode for master/worker nodes.

Update: Servers from `chronyconfig.content` can also be used in addition to the bastion_ip in bootstrap, master, worker nodes.

**Comment by yussufsh** [comment]
@schabrolles let us know if you would like to work on this one.

**Comment by schabrolles** [comment]
@yussufsh I'm currently on it and should be able to provide a PR in the following hours ... (just need time to test and clean the commit)

**Comment by yussufsh** [comment]
Thanks @schabrolles 
I have added your suggestion to the description to also add NTP servers to the list in cluster nodes.

One issue I think is to get the bastion IP in the playbook. We can use the inventory file for this. Replacing localhost with bastion IP.

**Comment by schabrolles** [comment]
> One issue I think is to get the bastion IP in the playbook. 

I use the variable `{{ ansible_default_ipv4.address }}` in the template. As it is run on the bastion itself, it returns the IP of the bastion.

**Comment by yussufsh** [comment]
> 
> I use the variable `{{ ansible_default_ipv4.address }}` in the template. As it is run on the bastion itself, it returns the IP of the bastion.

Ok.. did you debug that value for multi network bastion node? That could be one of the case when users add another network to the bastion node to provide internet access. Not sure if `ansible_default_ipv4.address` reads from the default route present on the machine?

**Comment by schabrolles** [comment]
@yussufsh Here is a new draft ... please have a look.
waiting for your feedback
