### ISSUE TITLE
Role nodes-config playbook fails when any host is in reboot state

### ISSUE THREAD

**Issue by yussufsh** [ocp-power-automation/ocp4-playbooks#62]
The issue happens when all nodes do not boot at once. For example, if master-1 is booted and available with ssh connection and master-2 delays ssh connection (say after 5 mins). Till the time all masters ssh connection check is complete master-1 may go into reboot state (via machineconfig). Playbook exits during such scenarios with 'unreachable' error for master-1.

Need to figure out a way for hosts not to wait for other nodes' ssh connections and run shell commands as soon as ssh is available for a particular host.

**Comment by yussufsh** [comment]
@Prajyot-Parab any update? The fix will be critical for release-4.5 and master branch.

**Comment by Prajyot-Parab** [comment]
@yussufsh using `strategy: free` in the playbook achieves the required parallelism but it also results in additional error handling requirement as `any_errors_fatal: true` is not supported with `strategy: free`, I am still exploring on how to do error handling in this scenario.

**Comment by yussufsh** [comment]
Going with `serial: 1` option here which will wait and execute commands on the rhcos nodes one by one.
