### ISSUE TITLE
Key systemd services don't auto-restart on bastion

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-playbooks#87]
Haproxy , named, squid service in bastion is not configured with Restart=always or Restart=on-failure. Consequently any crash of the service will not restart it automatically.

**Comment by yussufsh** [comment]
May be a contribution to the helpernode playbook?

**Comment by yussufsh** [comment]
Squid is in house so this issue is still valid for such services.

**Comment by bpradipt** [comment]
Either contribution to helpernode, or we can add a role in our playbook to create systemd dropin to add the configuration. Something like this 
```
cat <<EOF | sudo tee /etc/systemd/system/{haproxy, squid, named}.service.d/restart.conf
[Service]
Restart=always
EOF
```

**Comment by bpradipt** [comment]
Closed via https://github.com/ocp-power-automation/ocp4-playbooks/pull/93
