### ISSUE TITLE
Task "Create powervm-rmc project" fails on PowerVS

### ISSUE THREAD

**Issue by yussufsh** [ocp-power-automation/ocp4-playbooks#88]
Task "Create powervm-rmc project" is failing with "Service Unavailable" error.

See attached tail of TF console log for details. [power-rmc.txt](https://github.com/ocp-power-automation/ocp4-playbooks/files/5603123/power-rmc.txt)

**Comment by yussufsh** [comment]
@schabrolles Can you please have a look at this issue? At present I am not sure if it is random or the root cause for it.

I am able to create a namespace from bastion:

```
# oc create namespace new
namespace/new created
```

**Comment by yussufsh** [comment]
This could be API server issue.. or may be masters were in reboot cycle because of machineconfig change just before this?

After 3 tries it worked for me.

**Comment by schabrolles** [comment]
I got this issue yesterday during a cluster upgrade (not install) ... It was related to the AWS issue which support quay.io (where some container like powervm-rmc is located).

So I don't know if it could be related.

During our several cluster installation with powerVC terraform, we never add this issue...

One question, I notice in your log that the API was listening on 8443 port. Is that normal for powerVS ? On our regular OCP it is :6443 port.

**Comment by yussufsh** [comment]
No, PowerVS is also using 6443 port.

The 10.128.0.0/14 is cluster network.. so 10.128.0.63:8443 is some pod endpoint.

It has to do something with the cluster downtime at that moment.

**Comment by bpradipt** [comment]
@yussufsh is this still relevant ?

**Comment by yussufsh** [comment]
This is not seen again.. hence closing it.
